name: Generate Postman Collection

on:
   pull_request:
      branches: ["feat/docs"]
   workflow_dispatch:
jobs:
   generate-postman-collection:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Setup Node.js v16
           uses: actions/setup-node@v2
           with:
              node-version: "16.x"

         - name: Install dependencies
           run: npm install axios

         - name: Generate Postman Collection
           run: node postman-collection/transformer.js

         - name: Upload artifact
           uses: actions/upload-artifact@v2
           with:
              name: postman-collection
              path: postman-collection/example1.json
