name: Run Generate Data for DOCS

# change this feat/docs to master
on:
   push:
      branches: ["feat/docs"]

permissions: write-all

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Use Node.js
           uses: actions/setup-node@v3
           with:
              node-version: "16.x"

         - name: Install dependencies
           run: npm install axios

         - name: Run Node function and create file
           run: node Postman\ Collections/transformer.js

         - name: Commit changes
           run: |
              git switch -c version-branch
              git config --global user.email "test@zesty.io"
              git config --global user.name "Zesty Test"
              git add .
              git commit --allow-empty -m ":rocket: chore: bump Docs Data"
              git push origin version-branch:feat/docs

# change this feat/docs to master
